# Generated by Django 4.0.1 on 2022-01-11 20:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pen', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='memo',
            old_name='modified_date',
            new_name='created_date',
        ),
        migrations.RemoveField(
            model_name='memo',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='memo',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='memo',
            name='text',
        ),
        migrations.AddField(
            model_name='memo',
            name='body',
            field=models.CharField(default=None, max_length=10000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='memo',
            name='title',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='memo',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='memo',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
